# Site settings
title:       Bhuvan Rawal
email:       bhuvan@bhuvanrawal.me
author:      Bhuvan Rawal
description: "Code. Coffee. Repeat."
baseurl:     ""
url:         "http://bhuvanrawal.me"

# Google analytics
google_analytics: UA-58286706-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: bhuvanrawal
stackoverflow_id: 3646120
twitter_username: bhuvanrawal
google_plus_id: 115368800868963120427
linkedin_username: 120133982
bitcoin_url:
paypal_url:
flattr_button:
facebook_profileUrl: https://www.facebook.com/bhu1rawal 

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title/
sass:
compressed: true

disqus_shortname : bhuvanrawal

gems:
  - jekyll-sitemap

exclude: [tmp, Rakefile]

excerpt_separator: ""
