# Site settings
title:       Bhuvan Rawal
email:       bhu1rawal@gmail.com
author:      Bhuvan Rawal
description: "Code. Coffee. Repeat."
baseurl:     ""
url:         "http://bhuvanrawal.me"

# Google analytics
google_analytics: UA-53548208-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: bhuvanrawal
stackoverflow_id: bhuvanrawal
twitter_username: bhuvanrawal
google_plus_id: +bhu1rawal
linkedin_username: Bhuvan Rawal
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 5
sass:
compressed: true
