# Site settings
title:       Bhuvan Rawal
email:       bhu1rawal@gmail.com
author:      Bhuvan Rawal
description: "Code. Coffee. Repeat."
baseurl:     ""
url:         "http://bhuvanrawal.me"

# Google analytics
google_analytics: UA-58286706-1

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: bhuvanrawal
stackoverflow_id: bhuvan-rawal
twitter_username: bhuvanrawal
google_plus_id: /explore/bhu1rawal
linkedin_username: bhuvanrawal
bitcoin_url:
paypal_url:
flattr_button:
fb_profile_id: https://www.facebook.com/bhu1rawal 

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 5
sass:
compressed: true
